apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentpetclinic
  namespace: test-cs
spec:
  replicas: 3
  selector:
   matchLabels:
     app: petclinic
  template:
    metadata:
      labels:
        app: petclinic 
    spec:
       containers:
         - name: springcontainer
           image: chaitu1812/springpet:v1.26
           ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclincservcie
  namespace: test-cs
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
   - port: 8090
     targetPort: 8080
     nodePort: 32245
