apiVersion: apps/v1
kind: Deployment
metadata:
  name: newreplicaset
  namespace: test-ns
spec:
  replicas: 3
  startegy:
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 0 
    type: RollingUpdate
  selector:
   matchLabels:
     app: ram
  template:
    metadata:
      labels:
        app: ram
    spec:
       containers:
         - name: chatcontainer
           image: chaitu1812/springpet:v1.24
           ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: replicasetservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: ram
  ports:
   - port: 8090
     targetPort: 8080
     nodePort: 32245
