apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetdeployment
  namespace: test-ns
spec:
  replicas: 3
  selector:
   matchLabels:
     app: ram
  template:
    metadata:
      labels:
        app: ram
    spec:
       containers:
         - name: springcontainer
           image: chaitu1812/springpet:v1.22
           ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springpetservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: ram
  ports:
   - port: 8090
     targetPort: 8080
     nodePort: 32245
