apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpet:v1.26
  namespace: test-cs
spec:
  replicas: 3
  selector:
   matchLabels:
     app: springpet
  template:
    metadata:
      labels:
        app: springpet
    spec:
       containers:
         - name: springcontainer
           image: chaitu1812/springpet:v1.26
           ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springpet:v1.26
  namespace: test-cs
spec:
  type: NodePort
  selector:
    app: springpet
  ports:
   - port: 8090
     targetPort: 8080
     nodePort: 32245
